name: Test

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.18.6"

    - name: Run Tests
      run: |
        go test -v .

